import type { Metadata } from 'next';
import './globals.css';

export const viewport = {
  themeColor: '#ffffff',
};

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  manifest: '/manifest.json',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="font-gMedium min-h-screen bg-beige dark:bg-navy text-navy dark:text-lightBeige overflow-x-hidden">
        {children}
      </body>
    </html>
  );
}
